services:
  _defaults:
    autowire: true
    autoconfigure: true
  color_picker_custom:
    class: SevenGroupFrance\SuluRangeBundle\Content\Types\SuluRange
    tags: [{ name: "sulu.content.type", alias: "sulu_range" }]
