services:
  _defaults:
    autowire: true
    autoconfigure: true
  range:
    class: SevenGroupFrance\SuluRangeBundle\Content\Types\SuluRange
    tags: [{ name: "sulu.content.type", alias: "range" }]
